# istep0
include ekb/chips/p10/procedures/hwp/perv/p10_setup_ref_clock.mk
include ekb/chips/p10/procedures/hwp/perv/p10_clock_test.mk
include ekb/chips/p10/procedures/hwp/perv/p10_select_boot_master.mk
include ekb/chips/p10/procedures/hwp/perv/p10_setup_sbe_config.mk
include ekb/chips/p10/procedures/hwp/perv/p10_start_cbs.mk

# istep6-21
include ekb/chips/p10/procedures/hwp/istep/p10_do_fw_hb_istep.mk

# Procedure to check sbe status.
include ekb/chips/p10/procedures/hwp/sbe/p10_get_sbe_msg_register.mk

# Procedure required for poweroff.
include ekb/chips/p10/procedures/hwp/perv/p10_pre_poweroff.mk

# Procedure required for extract sbe rc
include ekb/chips/p10/procedures/hwp/perv/p10_extract_sbe_rc.mk
include ekb/chips/p10/procedures/hwp/lib/p10_ppe_utils.mk
include ekb/chips/p10/procedures/hwp/lib/p10_ppe_common.mk
include ekb/chips/ocmb/odyssey/procedures/hwp/perv/ody_extract_sbe_rc.mk

# Procedure required for generating sbe dump.
include ekb/chips/p10/procedures/hwp/lib/p10_pibmem_dump.mk
include ekb/chips/p10/procedures/hwp/lib/p10_pibms_reg_dump.mk
include ekb/chips/p10/procedures/hwp/lib/p10_ppe_state.mk
include ekb/chips/p10/procedures/hwp/lib/p10_sbe_localreg_dump.mk
include ekb/chips/ocmb/odyssey/procedures/hwp/utils/generic_utils.mk
include ekb/chips/ocmb/odyssey/procedures/hwp/utils/ody_ppe_utils.mk
include ekb/chips/ocmb/odyssey/procedures/hwp/utils/ody_ppe_state.mk

# Procedure required for sbe hreset
include ekb/chips/p10/procedures/hwp/perv/p10_sbe_hreset.mk
